[package]
name = "kubetool"
version = "0.1.0"
authors = ["Dave Try <dave.try@puppet.com>"]
edition = "2018"

[dependencies]
clap = {version = "2.32.0", features = ["yaml"]}
serde = "1.0"
serde_yaml = "0.8"

